// FAS-React/src/containers/Game/Details.tsx
import { isEmptyObject } from "jquery";
import { useEffect, useState } from "react";
import { useContext } from "react";
import { Link, useParams } from "react-router-dom";
import Loader from "../../components/Loader";
import { AppContext } from "../../context/AppContext";
import { BaseService } from "../../services/base-service";
import { EPageStatus } from "../../types/EPageStatus";
import { LeagueTableClient } from "../../dto/LeagueTableClient"
import { IRouteId } from "../../types/IRouteId";
import { Team } from "../../dto/Team";
import { LeagueTableTeam } from "../../dto/LeagueTableTeam";
import { LeagueGame } from "../../dto/LeagueGame";
import { GameEvent } from "../../dto/GameEvent"
import { TeamPerson } from "../../dto/TeamPerson";
import { GameTeamList } from "../../dto/GameTeamList";


const RowDisplay = (props: { gameEvent: GameEvent, leagueGame: LeagueGame}) => {
    return (
    <>
        <td>{ props.gameEvent.gameTime }</td>
        <td>{ props.gameEvent.eventType!.name }</td>
        <td>{ props.gameEvent.gameTeamList!.teamPerson!.person!.fullName }</td>
        <td>
            <div>{props.gameEvent.gameTeamList!.gameTeamId == props.leagueGame.homeTeam!.id? props.leagueGame.homeTeam!.team!.name :props.leagueGame.awayTeam!.team!.name }</div>
        </td>
    </>);
} 

const RowDisplay2 = (props: { person: GameTeamList }) => {
    return (
    <>
        <td rowSpan={1} colSpan={1}>{ props.person.teamPerson!.person!.firstName }</td>
        <td rowSpan={1} colSpan={1}>{ props.person.teamPerson!.person!.lastName }</td>
    </>);
}

const GameDetails = () => {
    const { id } = useParams() as IRouteId;
    const [pageStatus, setPageStatus] = useState({ pageStatus: EPageStatus.Loading, statusCode: -1 });
    const appState = useContext(AppContext);
    const [leagueGame, setLeagueGame] = useState({} as LeagueGame);
    const [gameEvents, setGameEvents] = useState([] as GameEvent[])

    const loadData = async () => {
        let resultLeagueGame = await BaseService.get<LeagueGame>("/LeagueTeam/" + id)
        let resultGameEvent = await BaseService.getAll<GameEvent>("/GameEvent/gameId=" + resultLeagueGame.data?.game?.id)
        if (resultLeagueGame.ok && resultLeagueGame.data && resultGameEvent.ok && resultGameEvent.data) {
            setPageStatus({ pageStatus: EPageStatus.OK, statusCode: 0 });
            setLeagueGame(resultLeagueGame.data);
            setGameEvents(resultGameEvent.data)
        } else {
            setPageStatus({ pageStatus: EPageStatus.Error, statusCode: resultLeagueGame.statusCode });
        }
    }

    useEffect(() => {
        loadData();
    }, []); // eslint-disable-line react-hooks/exhaustive-deps

    if(!isEmptyObject(leagueGame)){
        return (
            <>
                <div className="d-sm-flex align-items-center justify-content-center">
                    <div className="card shadow mb-4">
                        <div className="card-header py-3">
                            <div className="row d-sm-flex justify-content-between">
                                <h4 className="m-0 font-weight-bold text-primary">{ leagueGame.homeTeam!.team!.name }</h4>
                                <div className="d-sm-flex align-items-center justify-content-center">
                                    <h4 className="m-0 font-weight-bold text-primary">{ leagueGame.homeTeam!.scored }</h4>
                                    <h4 className="m-0 font-weight-bold text-primary">:</h4>
                                    <h4 className="m-0 font-weight-bold text-primary">{ leagueGame.awayTeam!.scored }</h4>
                                </div>
                                <h4 className="m-0 font-weight-bold text-primary">{leagueGame.awayTeam!.team!.name }</h4>
                            </div>
                        </div>
                        <div className="card-body">
                            <div id="dataTable_wrapper" className="dataTables_wrapper dt-bootstrap4">
                            <div className="row d-sm-flex align-items-center justify-content-between">
                                {appState.role==="Admin" || appState.role === "Referee"?
                                
                                <Link to={'/GameEvent/' + leagueGame.homeTeam!.id} className="btn btn-primary">
                                    <span className="icon text-white-50">
                                        <i className="fas fa-flag"></i>
                                    </span>
                                    <span className="text">Add game event</span>
                                </Link>
                                : null}
                                {appState.role==="Admin" || appState.role === "Referee"?
                                
                                <Link to={'/GameEvent/' + leagueGame.awayTeam!.id} className="btn btn-primary">
                                    <span className="icon text-white-50">
                                        <i className="fas fa-flag"></i>
                                    </span>
                                    <span className="text">Add game event</span>
                                </Link>
                                : null}
                           </div>
                            <div className="row d-sm-flex align-items-center justify-content-center">
                                <div className="h2 text-black-800 text-center">Game events</div>
                                {gameEvents.length !== 0? 
                                <table className="table table-bordered dataTable" id="dataTable" cellSpacing={0} role="grid" aria-describedby="dataTable_info">
                                <thead>
                                <tr role="row">
                                    <th rowSpan={1} colSpan={1}>Game Time</th>
                                    <th rowSpan={1} colSpan={1}>GameEvents</th>
                                    <th rowSpan={1} colSpan={1}>Player</th>
                                    <th rowSpan={1} colSpan={1}>Team Name</th>
                                </tr>
                                </thead>
                                <tbody>
                                    {gameEvents!.map(gameEvent => 
                                        <tr key={gameEvent.id.toString()}>
                                            <RowDisplay gameEvent={gameEvent} leagueGame={leagueGame}/>
                                        </tr>
                                        )}
                                </tbody>
                                </table>: null}
                                
                            </div>

                            <div className="row d-sm-flex align-items-center justify-content-center">

                                <div className="col-sm-6">
                                    <div className="h4 text-black-800 text-center">In starting lineup</div>

                                    <table className="table table-bordered dataTable" id="dataTable" width="100%" cellSpacing={0} role="grid" aria-describedby="dataTable_info">
                                        <thead>
                                        <tr role="row">
                                            <th rowSpan={1} colSpan={1}>FirstName</th>
                                            <th rowSpan={1} colSpan={1}>LastName</th>
                                        </tr>
                                        </thead> 
                                        
                                         <tbody>
                                            {leagueGame.homeTeamList!.map(person => 
                                                person.inStartingLineUp?
                                                <tr key={person.id.toString()}>
                                                    <RowDisplay2 person={person}/>
                                                </tr>: null
                                            )}
                                            <tr>
                                                <td rowSpan={2} colSpan={2}>
                                                    <div className="h4 text-black-800 text-center">
                                                        Subsitutions
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr></tr>
                                            {leagueGame.homeTeamList!.map(person => 
                                                !person.inStartingLineUp && !person.staff?
                                                <tr key={person.id.toString()}>
                                                    <RowDisplay2 person={person}/>
                                                </tr>: null
                                            )}
                                            <tr role="row" className="text-center">
                                                <td rowSpan={2} colSpan={2}>
                                                    <div className="h4 text-black-800 text-center">
                                                        Staff
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr></tr>
    
                                            {leagueGame.homeTeamList!.map(person => 
                                                
                                                    person.staff?
                                                        person.person?
                                                        <tr key={person.id.toString()}>
                                                        <RowDisplay2 person={person}/>
                                                        </tr>
                                                        :
                                                        <tr>
                                                            <td rowSpan={1} colSpan={1}>{ person.person!.firstName }</td>
                                                            <td rowSpan={1} colSpan={1}>{ person.person!.lastName }</td>
                                                        </tr>
                                                    :null
                                                    
                                                
                                            )}
                                        </tbody>
                                    </table>
                                </div>

                                <div className="col-sm-6">

                                    <div className="h4 text-black-800 text-center">In starting lineup</div>

                                    <table className="table table-bordered dataTable" id="dataTable" width="100%" cellSpacing="0" role="grid" aria-describedby="dataTable_info">
                                        <thead>
                                        <tr role="row">
                                            <th rowSpan={1} colSpan={1}>FirstName</th>
                                            <th rowSpan={1} colSpan={1}>LastName</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                            {leagueGame.awayTeamList!.map(person => 
                                                person.inStartingLineUp?
                                                <tr key={person.id.toString()}>
                                                    <RowDisplay2 person={person}/>
                                                </tr>: null
                                            )}
                                            <tr>
                                                <td rowSpan={2} colSpan={2}>
                                                    <div className="h4 text-black-800 text-center">
                                                        Subsitutions
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr></tr>
                                            {leagueGame.awayTeamList!.map(person => 
                                                !person.inStartingLineUp && !person.staff?
                                                <tr key={person.id.toString()}>
                                                    <RowDisplay2 person={person}/>
                                                </tr>: null
                                            )}
                                            <tr role="row" className="text-center">
                                                <td rowSpan={2} colSpan={2}>
                                                    <div className="h4 text-black-800 text-center">
                                                        Staff
                                                    </div>
                                                </td>
                                            </tr>
                                            <tr></tr>
    
                                            {leagueGame.awayTeamList!.map(person => 
                                                
                                                    person.staff?
                                                        person.person?
                                                        <tr key={person.id.toString()}>
                                                        <RowDisplay2 person={person}/>
                                                        </tr>
                                                        :
                                                        <tr>
                                                            <td rowSpan={1} colSpan={1}>{ person.person!.firstName }</td>
                                                            <td rowSpan={1} colSpan={1}>{ person.person!.lastName }</td>
                                                        </tr>
                                                    :null
                                                    
                                                
                                            )}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>
            </>
        );
    }else{
        return (
            <>
                <Loader {...pageStatus} />
            </>
        );
    }
}
export default GameDetails;

// FAS-Vue/src/views/Game/Details.vue
<template>
    <div v-if="gate">
        <div class="d-sm-flex align-items-center justify-content-center">
            <div class="card shadow mb-4" style="width: 80%;">
                <div class="card-header py-3">
                    <div class="row d-sm-flex justify-content-between">
                        <h4 class="m-0 font-weight-bold text-primary">{{ LeagueGame.homeTeam.team.name }}</h4>
                        <div class="d-sm-flex align-items-center justify-content-center">
                            <h4 class="m-0 font-weight-bold text-primary">{{ LeagueGame.homeTeam.scored }}</h4>
                            <h4 class="m-0 font-weight-bold text-primary">:</h4>
                            <h4 class="m-0 font-weight-bold text-primary">{{ LeagueGame.awayTeam.scored }}</h4>
                        </div>
                        <h4 class="m-0 font-weight-bold text-primary">{{ LeagueGame.awayTeam.team.name }}</h4>
                    </div>
                </div>
                <div class="card-body">
                    <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4" style="width: 100%;">

                    <div class="row d-sm-flex align-items-center justify-content-between" v-if="role === 'Admin' || role == 'Referee'"><router-link :to="'/GameEvent/' + LeagueGame.homeTeam.id" class="btn btn-primary">
                            <span class="icon text-white-50">
                                <i class="fas fa-flag"></i>
                            </span>
                            <span class="text">Add game event</span>
                        </router-link>
                        <router-link :to="'/GameEvent/' + LeagueGame.awayTeam.id" class="btn btn-primary">
                            <span class="icon text-white-50">
                                <i class="fas fa-flag"></i>
                            </span>
                            <span class="text">Add game event</span>
                        </router-link>

                    </div>
                    <div class="row d-sm-flex align-items-center justify-content-center">
                        <div class="h2 text-black-800 text-center">Game events</div>
                        <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;"
                        v-if="LeagueGame.game.gameEvents.Count != 0">
                                <thead>
                                <tr role="row">
                                    <th rowspan="1" colspan="1">Game Time</th>
                                    <th rowspan="1" colspan="1">GameEvents</th>
                                    <th rowspan="1" colspan="1">Player</th>
                                    <th rowspan="1" colspan="1">Team Name</th>
                                </tr>
                                </thead>
                                <tbody>
                                    <tr v-for="item in LeagueGame.game.gameEvents" :key="item.gameTime">
                                        <td>{{ item.gameTime }}</td>
                                        <td>{{ item.eventType.name }}</td>
                                        <td>{{ item.gameTeamList.teamPerson.person.fullName }}</td>
                                        <td>
                                            <div v-if="item.gameTeamList.gameTeamId == LeagueGame.homeTeam.id">{{ LeagueGame.homeTeam.team.name }}</div>
                                            <div v-else>{{ LeagueGame.awayTeam.team.name }}</div>
                                        </td>
                                    </tr>
                                </tbody>
                        </table>
                    </div>

                    <div class="row d-sm-flex align-items-center justify-content-center">

                        <div class="col-sm-6">
                            <div class="h4 text-black-800 text-center">In starting lineup</div>

                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                <tr role="row">
                                    <th rowspan="1" colspan="1">FirstName</th>
                                    <th rowspan="1" colspan="1">LastName</th>
                                </tr>
                                </thead>

                                <tbody v-if="LeagueGame.homeTeamList.length !== 0">
                                    <tr v-for="item in LeagueGame.homeTeamList" :key="item.id" role="row">
                                            <td rowspan="1" colspan="1">{{ item.teamPerson.person.firstName }}</td>
                                            <td rowspan="1" colspan="1">{{ item.teamPerson.person.lastName }}</td>
                                        </tr>
                                    <tr role="row">
                                        <td rowspan="2" colspan="2">
                                            <div class="h4 text-black-800 text-center">
                                                Subsitutions
                                            </div>
                                        </td>
                                    </tr>
                                    <tr></tr>
                                    <tr v-for="item in LeagueGame.homeTeamList.filter(item => !item.inStartingLineup && !item.staff)" :key="item.id" role="row">
                                        <td rowspan="1" colspan="1">{{ item.teamPerson.person.firstName }}</td>
                                        <td rowspan="1" colspan="1">{{ item.teamPerson.person.lastName }}</td>
                                    </tr>

                                    <tr role="row" class="text-center">
                                        <td rowspan="2" colspan="2">
                                            <div class="h4 text-black-800 text-center">
                                                Staff
                                            </div>
                                        </td>
                                    </tr>
                                    <tr></tr>
                                    <tr v-for="item in LeagueGame.homeTeamList.filter(item => item.staff)" :key="item.id" role="row">
                                        <td rowspan="1" colspan="1" v-if="item.person != null">{{ item.person.firstName }}</td>
                                        <td rowspan="1" colspan="1" v-if="item.person != null">{{ item.person.lastName }}</td>
                                        <td rowspan="1" colspan="1" v-if="item.person == null">{{ item.teamPerson.person.firstName }}</td>
                                        <td rowspan="1" colspan="1" v-if="item.person == null">{{ item.teamPerson.person.lastName }}</td>
                                    </tr>
                                </tbody>
                                <tbody v-else>
                                    <div v-if="role !== null">
                                        <router-link :to="'/GameTeamList/Create/' + LeagueGame.homeTeam.id" class="btn btn-primary">
                                            <span class="icon text-white-50">
                                                <i class="fas fa-flag"></i>
                                            </span>
                                            <span class="text">Add starting lineup</span>
                                        </router-link>
                                    </div>
                                </tbody>
                            </table>
                        </div>

                        <div class="col-sm-6">

                            <div class="h4 text-black-800 text-center">In starting lineup</div>

                            <table class="table table-bordered dataTable" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
                                <thead>
                                <tr role="row">
                                    <th rowspan="1" colspan="1">FirstName</th>
                                    <th rowspan="1" colspan="1">LastName</th>
                                </tr>
                                </thead>
                                <tbody v-if="LeagueGame.awayTeamList.length !== 0">
                                    <tr v-for="item in LeagueGame.awayTeamList" :key="item.id" role="row">
                                        <td rowspan="1" colspan="1">{{ item.teamPerson.person.firstName }}</td>
                                        <td rowspan="1" colspan="1">{{ item.teamPerson.person.lastName }}</td>
                                    </tr>
                                    <tr role="row">
                                        <td rowspan="2" colspan="2">
                                            <div class="h4 text-black-800 text-center">
                                                Subsitutions
                                            </div>
                                        </td>
                                    </tr>
                                    <tr></tr>
                                    <tr v-for="item in LeagueGame.awayTeamList.filter(item => !item.inStartingLineup && !item.staff)" :key="item.id" role="row">
                                        <td rowspan="1" colspan="1">{{ item.teamPerson.person.firstName }}</td>
                                        <td rowspan="1" colspan="1">{{ item.teamPerson.person.lastName }}</td>
                                    </tr>

                                    <tr role="row" class="text-center">
                                        <td rowspan="2" colspan="2">
                                            <div class="h4 text-black-800 text-center">
                                                Staff
                                            </div>
                                        </td>
                                    </tr>
                                    <tr></tr>
                                    <tr v-for="item in LeagueGame.awayTeamList.filter(item => item.staff)" :key="item.id" role="row">
                                        <td rowspan="1" colspan="1" v-if="item.person != null">{{ item.person.firstName }}</td>
                                        <td rowspan="1" colspan="1" v-if="item.person != null">{{ item.person.lastName }}</td>
                                        <td rowspan="1" colspan="1" v-if="item.person == null">{{ item.teamPerson.person.firstName }}</td>
                                        <td rowspan="1" colspan="1" v-if="item.person == null">{{ item.teamPerson.person.lastName }}</td>
                                    </tr>
                                </tbody>
                                <tbody v-else>
                                    <div v-if="role !== null">
                                        <router-link :to="'/GameTeamList/Create/' + LeagueGame.awayTeam.id" class="btn btn-primary">
                                            <span class="icon text-white-50">
                                                <i class="fas fa-flag"></i>
                                            </span>
                                            <span class="text">Add starting lineup</span>
                                        </router-link>
                                    </div>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script lang="ts">
import { Options, Vue } from "vue-class-component";
import { PageLoader } from "@/types/PageLoader";
import { EPageStatus } from "@/types/EPageStatus";
import { BaseService } from "@/services/base-service";
import Loader from "@/components/Loader.vue";
import store from "@/store/index";
import { LeagueGame } from "@/domain/DTO/LeagueGame";
import { GameEvent } from "@/domain/DTO/GameEvent";

@Options({
    components: { Loader },
    props: { id: String },
})

export default class GameDetails extends Vue {
    pageLoader: PageLoader = { pageStatus: EPageStatus.Loading, statusCode: -1 };
    id!:string;
    LeagueGame?: LeagueGame;
    gate: boolean = false;
    role?: string

    async mounted(): Promise<void> {
        const resultLeagueGame = await BaseService.get<LeagueGame>("LeagueTeam/" + this.id)
        const resultGameEvent = await BaseService.getAll<GameEvent>("GameEvent/gameId=" + resultLeagueGame.data?.game?.id)
        if (resultLeagueGame.ok && resultLeagueGame.data &&
        resultGameEvent.ok && resultGameEvent.data
        ) {
            this.pageLoader = { pageStatus: EPageStatus.OK, statusCode: 0 }
            this.role = store.state.role
            this.LeagueGame = resultLeagueGame.data;
            this.LeagueGame.game!.gameEvents = resultGameEvent.data;
            this.gate = true;
        } else {
            this.pageLoader = {
                pageStatus: EPageStatus.Error,
                statusCode: (!resultLeagueGame.ok ? resultLeagueGame
                    : resultLeagueGame).statusCode
            }
        }
    }
}

</script>
