// FAS-React/src/components/Header.tsx
import { useContext, useState } from "react";
import { AppContext } from "../context/AppContext";
import { Link, Redirect } from "react-router-dom";

const Header = () => {
    const appState = useContext(AppContext);
    const [submit, setSubmit] = useState("");

    const logOutClicked = (e: Event, uri: string) => {
        e.preventDefault();
        appState.clearAuthInfo(appState);
        setSubmit(uri);
    }
    
    return (
        <>
            { submit !== "" ? <Redirect to={submit} /> : null}
            <header className="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                <button className="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="navbar-collapse collapse d-flex justify-content-end">
                    <ul className="navbar-nav float-right">
                        <li className="nav-item">
                            <Link to="/Identity/Profile" className="nav-link btn btn-link text-dark" title="Manage">
                                Hello! {appState.firstName} {appState.lastName}
                            </Link>
                        </li>
                        <li className="nav-item">
                            {appState.token !== null? <button onClick={(e) => logOutClicked(e.nativeEvent, "/Home/Index")} className="nav-link btn btn-link text-dark">Logout</button>:
                            <button onClick={(e) => logOutClicked(e.nativeEvent, "/Identity/Login")} className="nav-link btn btn-link text-dark">Login</button>
                            }
                            
                        </li>
                    </ul>
                </div>
            </header>
        </>
    );
}

export default Header;

// FAS-Vue/src/components/Header.vue
<template>
    <header class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
        <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target=".navbar-collapse"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
        >
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse collapse d-flex justify-content-end">
            <ul class="navbar-nav float-right">
                <li class="nav-item" v-if="!token">
                    <router-link
                        to="/identity/login"
                        class="nav-link text-dark"
                        >Login</router-link
                    >
                </li>

                <li class="nav-item" v-if="token" >
                    <a
                        href="#"
                        class="nav-link text-dark"
                        @click="logOut()"
                        >Logout
                    </a>
                </li>
            </ul>
        </div>
    </header>
</template>
<script lang="ts">
import { Options, Vue } from "vue-class-component";
import store from "@/store/index";

@Options({
    components: {},
    props: {},
})
export default class Header extends Vue {
    get token(): string | null {
        return store.state.token;
    }

    logOut(): void {
        store.commit("logOut");
        this.$router.push("/");
    }
}
</script>
